### ISSUE TITLE
Unable to find template error after installing

### ISSUE THREAD

**Issue by ambidustrious** [barrelstrength/craft-sprout-sitemaps#10]
I just installed and added the license. When I load the plugin I get the following error:

Twig Template Loading Error – craft\web\twig\TemplateLoaderException
Unable to find the template “sprout-sitemaps/settings”.

**Comment by dineufeld** [comment]
Same problem here. Opening /sitemap.xml gives an Internal Server Error

**Comment by ambidustrious** [comment]
For me, the error appears when I load the settings page.

**Comment by dineufeld** [comment]
For me both, the settings sage and sitemap.xml

**Comment by BenParizek** [comment]
@ambidustrious @dineufeld Thanks for reporting. Looking into it. We'll update this thread once we have a fix.

**Comment by andrelopez** [comment]
Hi @ambidustrious @dineufeld We're unable to recreate this issue. Could you please tell us what is your Craft CMS and Sprout Sitemaps version?

**Comment by ambidustrious** [comment]
Craft: 3.3.1.0
Sprite Sitemaps: 1.0.2

**Comment by ambidustrious** [comment]
Oddly enough... I'm no longer receiving the error... but...

I've enabled the sitemap on 2 channels and the sitemap isn't rendering the entries

You can view the output here:
http://seventhecho.com/sitemap.xml

**Comment by BenParizek** [comment]
Can you confirm that you have Sitemaps enabled in the Sitemaps settings?

@ambidustrious I'm seeing a sitemap output at the link you provide above.
![image](https://user-images.githubusercontent.com/309735/67052048-027a1400-f10b-11e9-809f-502bfc6391fa.png)

The top-level sitemap is a sitemap index files so it just lists a more specific sitemap file for each section you have enabled in your sitemap. Visiting the individual sitemap links will output the list of more familiar page URLs.

@dineufeld Are you still experiencing the error? I think we'll need more info to help troubleshoot so if you could provide any screenshots or logs it would be helpful.

**Comment by ambidustrious** [comment]
![image](https://user-images.githubusercontent.com/22107826/67052962-e4fa7980-f10d-11e9-91f6-efad125f1eaf.png)

![image](https://user-images.githubusercontent.com/22107826/67052970-f2176880-f10d-11e9-8785-b8a53156b65a.png)

![image](https://user-images.githubusercontent.com/22107826/67052985-ffccee00-f10d-11e9-9ccc-673409e91cf0.png)

![image](https://user-images.githubusercontent.com/22107826/67052994-052a3880-f10e-11e9-8c35-f7b6ed1d1e8d.png)

**Comment by ambidustrious** [comment]
Happy to give you access to the site if that's helpful

**Comment by BenParizek** [comment]
@ambidustrious What issue are we trying to solve here?

Your sitemapindex has two sitemaps it links to:
http://seventhecho.com/sitemap.xml

The first is your blog, which is listing 4 posts and in your screenshot you have 4 posts enabled in the blog section:
http://seventhecho.com/sitemap-OC7LSSBeG7_h-1.xml

The second appears to be the Pages channel, which also appears to be listing all the URLs in the screenshot you provided:
http://seventhecho.com/sitemap-enCs_zHeYgBV-1.xml

What am I missing?

**Comment by ambidustrious** [comment]
Got it - I actually didn't realize that was a valid format for sitemap.xml - I assumed it would list url on that page vs. linking to other pages. - So long story short... I don't know why it was throwing a 500 error at the beginning of this thread, but it looks like it's all resolved now.

Thank you for your attention on it.
